export type PhonePrefix = { code: string; flag: string; label: string }

export const PHONE_PREFIXES: PhonePrefix[] = [
  { code: '+93',   flag: '🇦🇫', label: 'Afghanistan' },
  { code: '+27',   flag: '🇿🇦', label: 'Afrique du Sud' },
  { code: '+355',  flag: '🇦🇱', label: 'Albanie' },
  { code: '+213',  flag: '🇩🇿', label: 'Algérie' },
  { code: '+49',   flag: '🇩🇪', label: 'Allemagne' },
  { code: '+376',  flag: '🇦🇩', label: 'Andorre' },
  { code: '+244',  flag: '🇦🇴', label: 'Angola' },
  { code: '+1268', flag: '🇦🇬', label: 'Antigua-et-Barbuda' },
  { code: '+966',  flag: '🇸🇦', label: 'Arabie saoudite' },
  { code: '+54',   flag: '🇦🇷', label: 'Argentine' },
  { code: '+374',  flag: '🇦🇲', label: 'Arménie' },
  { code: '+61',   flag: '🇦🇺', label: 'Australie' },
  { code: '+43',   flag: '🇦🇹', label: 'Autriche' },
  { code: '+994',  flag: '🇦🇿', label: 'Azerbaïdjan' },
  { code: '+1242', flag: '🇧🇸', label: 'Bahamas' },
  { code: '+973',  flag: '🇧🇭', label: 'Bahreïn' },
  { code: '+880',  flag: '🇧🇩', label: 'Bangladesh' },
  { code: '+1246', flag: '🇧🇧', label: 'Barbade' },
  { code: '+375',  flag: '🇧🇾', label: 'Bélarus' },
  { code: '+32',   flag: '🇧🇪', label: 'Belgique' },
  { code: '+501',  flag: '🇧🇿', label: 'Belize' },
  { code: '+229',  flag: '🇧🇯', label: 'Bénin' },
  { code: '+975',  flag: '🇧🇹', label: 'Bhoutan' },
  { code: '+591',  flag: '🇧🇴', label: 'Bolivie' },
  { code: '+387',  flag: '🇧🇦', label: 'Bosnie-Herzégovine' },
  { code: '+267',  flag: '🇧🇼', label: 'Botswana' },
  { code: '+55',   flag: '🇧🇷', label: 'Brésil' },
  { code: '+673',  flag: '🇧🇳', label: 'Brunéi' },
  { code: '+359',  flag: '🇧🇬', label: 'Bulgarie' },
  { code: '+226',  flag: '🇧🇫', label: 'Burkina Faso' },
  { code: '+257',  flag: '🇧🇮', label: 'Burundi' },
  { code: '+238',  flag: '🇨🇻', label: 'Cabo Verde' },
  { code: '+855',  flag: '🇰🇭', label: 'Cambodge' },
  { code: '+237',  flag: '🇨🇲', label: 'Cameroun' },
  { code: '+1',    flag: '🇨🇦', label: 'Canada' },
  { code: '+236',  flag: '🇨🇫', label: 'Centrafrique' },
  { code: '+56',   flag: '🇨🇱', label: 'Chili' },
  { code: '+86',   flag: '🇨🇳', label: 'Chine' },
  { code: '+357',  flag: '🇨🇾', label: 'Chypre' },
  { code: '+57',   flag: '🇨🇴', label: 'Colombie' },
  { code: '+269',  flag: '🇰🇲', label: 'Comores' },
  { code: '+242',  flag: '🇨🇬', label: 'Congo (Brazzaville)' },
  { code: '+243',  flag: '🇨🇩', label: 'Congo (Kinshasa)' },
  { code: '+82',   flag: '🇰🇷', label: 'Corée du Sud' },
  { code: '+850',  flag: '🇰🇵', label: 'Corée du Nord' },
  { code: '+506',  flag: '🇨🇷', label: 'Costa Rica' },
  { code: '+225',  flag: '🇨🇮', label: "Côte d'Ivoire" },
  { code: '+385',  flag: '🇭🇷', label: 'Croatie' },
  { code: '+53',   flag: '🇨🇺', label: 'Cuba' },
  { code: '+45',   flag: '🇩🇰', label: 'Danemark' },
  { code: '+253',  flag: '🇩🇯', label: 'Djibouti' },
  { code: '+1767', flag: '🇩🇲', label: 'Dominique' },
  { code: '+20',   flag: '🇪🇬', label: 'Égypte' },
  { code: '+971',  flag: '🇦🇪', label: 'Émirats arabes unis' },
  { code: '+593',  flag: '🇪🇨', label: 'Équateur' },
  { code: '+291',  flag: '🇪🇷', label: 'Érythrée' },
  { code: '+34',   flag: '🇪🇸', label: 'Espagne' },
  { code: '+268',  flag: '🇸🇿', label: 'Eswatini' },
  { code: '+1',    flag: '🇺🇸', label: 'États-Unis' },
  { code: '+251',  flag: '🇪🇹', label: 'Éthiopie' },
  { code: '+679',  flag: '🇫🇯', label: 'Fidji' },
  { code: '+358',  flag: '🇫🇮', label: 'Finlande' },
  { code: '+33',   flag: '🇫🇷', label: 'France' },
  { code: '+241',  flag: '🇬🇦', label: 'Gabon' },
  { code: '+220',  flag: '🇬🇲', label: 'Gambie' },
  { code: '+995',  flag: '🇬🇪', label: 'Géorgie' },
  { code: '+233',  flag: '🇬🇭', label: 'Ghana' },
  { code: '+30',   flag: '🇬🇷', label: 'Grèce' },
  { code: '+1473', flag: '🇬🇩', label: 'Grenade' },
  { code: '+502',  flag: '🇬🇹', label: 'Guatemala' },
  { code: '+224',  flag: '🇬🇳', label: 'Guinée' },
  { code: '+240',  flag: '🇬🇶', label: 'Guinée équatoriale' },
  { code: '+245',  flag: '🇬🇼', label: 'Guinée-Bissau' },
  { code: '+592',  flag: '🇬🇾', label: 'Guyana' },
  { code: '+509',  flag: '🇭🇹', label: 'Haïti' },
  { code: '+504',  flag: '🇭🇳', label: 'Honduras' },
  { code: '+36',   flag: '🇭🇺', label: 'Hongrie' },
  { code: '+91',   flag: '🇮🇳', label: 'Inde' },
  { code: '+62',   flag: '🇮🇩', label: 'Indonésie' },
  { code: '+964',  flag: '🇮🇶', label: 'Irak' },
  { code: '+98',   flag: '🇮🇷', label: 'Iran' },
  { code: '+353',  flag: '🇮🇪', label: 'Irlande' },
  { code: '+354',  flag: '🇮🇸', label: 'Islande' },
  { code: '+972',  flag: '🇮🇱', label: 'Israël' },
  { code: '+39',   flag: '🇮🇹', label: 'Italie' },
  { code: '+1876', flag: '🇯🇲', label: 'Jamaïque' },
  { code: '+81',   flag: '🇯🇵', label: 'Japon' },
  { code: '+962',  flag: '🇯🇴', label: 'Jordanie' },
  { code: '+7',    flag: '🇰🇿', label: 'Kazakhstan' },
  { code: '+254',  flag: '🇰🇪', label: 'Kenya' },
  { code: '+996',  flag: '🇰🇬', label: 'Kirghizstan' },
  { code: '+686',  flag: '🇰🇮', label: 'Kiribati' },
  { code: '+383',  flag: '🇽🇰', label: 'Kosovo' },
  { code: '+965',  flag: '🇰🇼', label: 'Koweït' },
  { code: '+856',  flag: '🇱🇦', label: 'Laos' },
  { code: '+266',  flag: '🇱🇸', label: 'Lesotho' },
  { code: '+371',  flag: '🇱🇻', label: 'Lettonie' },
  { code: '+961',  flag: '🇱🇧', label: 'Liban' },
  { code: '+231',  flag: '🇱🇷', label: 'Liberia' },
  { code: '+218',  flag: '🇱🇾', label: 'Libye' },
  { code: '+423',  flag: '🇱🇮', label: 'Liechtenstein' },
  { code: '+370',  flag: '🇱🇹', label: 'Lituanie' },
  { code: '+352',  flag: '🇱🇺', label: 'Luxembourg' },
  { code: '+261',  flag: '🇲🇬', label: 'Madagascar' },
  { code: '+60',   flag: '🇲🇾', label: 'Malaisie' },
  { code: '+265',  flag: '🇲🇼', label: 'Malawi' },
  { code: '+960',  flag: '🇲🇻', label: 'Maldives' },
  { code: '+223',  flag: '🇲🇱', label: 'Mali' },
  { code: '+356',  flag: '🇲🇹', label: 'Malte' },
  { code: '+212',  flag: '🇲🇦', label: 'Maroc' },
  { code: '+692',  flag: '🇲🇭', label: 'Marshall' },
  { code: '+230',  flag: '🇲🇺', label: 'Maurice' },
  { code: '+222',  flag: '🇲🇷', label: 'Mauritanie' },
  { code: '+52',   flag: '🇲🇽', label: 'Mexique' },
  { code: '+691',  flag: '🇫🇲', label: 'Micronésie' },
  { code: '+373',  flag: '🇲🇩', label: 'Moldavie' },
  { code: '+377',  flag: '🇲🇨', label: 'Monaco' },
  { code: '+976',  flag: '🇲🇳', label: 'Mongolie' },
  { code: '+382',  flag: '🇲🇪', label: 'Monténégro' },
  { code: '+258',  flag: '🇲🇿', label: 'Mozambique' },
  { code: '+95',   flag: '🇲🇲', label: 'Myanmar' },
  { code: '+264',  flag: '🇳🇦', label: 'Namibie' },
  { code: '+674',  flag: '🇳🇷', label: 'Nauru' },
  { code: '+977',  flag: '🇳🇵', label: 'Népal' },
  { code: '+505',  flag: '🇳🇮', label: 'Nicaragua' },
  { code: '+227',  flag: '🇳🇪', label: 'Niger' },
  { code: '+234',  flag: '🇳🇬', label: 'Nigéria' },
  { code: '+47',   flag: '🇳🇴', label: 'Norvège' },
  { code: '+64',   flag: '🇳🇿', label: 'Nouvelle-Zélande' },
  { code: '+968',  flag: '🇴🇲', label: 'Oman' },
  { code: '+256',  flag: '🇺🇬', label: 'Ouganda' },
  { code: '+998',  flag: '🇺🇿', label: 'Ouzbékistan' },
  { code: '+92',   flag: '🇵🇰', label: 'Pakistan' },
  { code: '+680',  flag: '🇵🇼', label: 'Palaos' },
  { code: '+970',  flag: '🇵🇸', label: 'Palestine' },
  { code: '+507',  flag: '🇵🇦', label: 'Panama' },
  { code: '+675',  flag: '🇵🇬', label: 'Papouasie-Nouvelle-Guinée' },
  { code: '+595',  flag: '🇵🇾', label: 'Paraguay' },
  { code: '+31',   flag: '🇳🇱', label: 'Pays-Bas' },
  { code: '+51',   flag: '🇵🇪', label: 'Pérou' },
  { code: '+63',   flag: '🇵🇭', label: 'Philippines' },
  { code: '+48',   flag: '🇵🇱', label: 'Pologne' },
  { code: '+351',  flag: '🇵🇹', label: 'Portugal' },
  { code: '+974',  flag: '🇶🇦', label: 'Qatar' },
  { code: '+1809', flag: '🇩🇴', label: 'Rép. dominicaine' },
  { code: '+40',   flag: '🇷🇴', label: 'Roumanie' },
  { code: '+44',   flag: '🇬🇧', label: 'Royaume-Uni' },
  { code: '+7',    flag: '🇷🇺', label: 'Russie' },
  { code: '+250',  flag: '🇷🇼', label: 'Rwanda' },
  { code: '+1869', flag: '🇰🇳', label: 'Saint-Christophe-et-Niévès' },
  { code: '+378',  flag: '🇸🇲', label: 'Saint-Marin' },
  { code: '+1784', flag: '🇻🇨', label: 'Saint-Vincent-et-les-Grenadines' },
  { code: '+1758', flag: '🇱🇨', label: 'Sainte-Lucie' },
  { code: '+677',  flag: '🇸🇧', label: 'Salomon' },
  { code: '+503',  flag: '🇸🇻', label: 'Salvador' },
  { code: '+685',  flag: '🇼🇸', label: 'Samoa' },
  { code: '+239',  flag: '🇸🇹', label: 'São Tomé-et-Príncipe' },
  { code: '+221',  flag: '🇸🇳', label: 'Sénégal' },
  { code: '+381',  flag: '🇷🇸', label: 'Serbie' },
  { code: '+248',  flag: '🇸🇨', label: 'Seychelles' },
  { code: '+232',  flag: '🇸🇱', label: 'Sierra Leone' },
  { code: '+65',   flag: '🇸🇬', label: 'Singapour' },
  { code: '+421',  flag: '🇸🇰', label: 'Slovaquie' },
  { code: '+386',  flag: '🇸🇮', label: 'Slovénie' },
  { code: '+252',  flag: '🇸🇴', label: 'Somalie' },
  { code: '+249',  flag: '🇸🇩', label: 'Soudan' },
  { code: '+211',  flag: '🇸🇸', label: 'Soudan du Sud' },
  { code: '+94',   flag: '🇱🇰', label: 'Sri Lanka' },
  { code: '+46',   flag: '🇸🇪', label: 'Suède' },
  { code: '+41',   flag: '🇨🇭', label: 'Suisse' },
  { code: '+597',  flag: '🇸🇷', label: 'Suriname' },
  { code: '+963',  flag: '🇸🇾', label: 'Syrie' },
  { code: '+992',  flag: '🇹🇯', label: 'Tadjikistan' },
  { code: '+255',  flag: '🇹🇿', label: 'Tanzanie' },
  { code: '+235',  flag: '🇹🇩', label: 'Tchad' },
  { code: '+420',  flag: '🇨🇿', label: 'Tchéquie' },
  { code: '+66',   flag: '🇹🇭', label: 'Thaïlande' },
  { code: '+670',  flag: '🇹🇱', label: 'Timor oriental' },
  { code: '+228',  flag: '🇹🇬', label: 'Togo' },
  { code: '+676',  flag: '🇹🇴', label: 'Tonga' },
  { code: '+1868', flag: '🇹🇹', label: 'Trinité-et-Tobago' },
  { code: '+216',  flag: '🇹🇳', label: 'Tunisie' },
  { code: '+993',  flag: '🇹🇲', label: 'Turkménistan' },
  { code: '+90',   flag: '🇹🇷', label: 'Turquie' },
  { code: '+688',  flag: '🇹🇻', label: 'Tuvalu' },
  { code: '+380',  flag: '🇺🇦', label: 'Ukraine' },
  { code: '+598',  flag: '🇺🇾', label: 'Uruguay' },
  { code: '+678',  flag: '🇻🇺', label: 'Vanuatu' },
  { code: '+58',   flag: '🇻🇪', label: 'Venezuela' },
  { code: '+84',   flag: '🇻🇳', label: 'Vietnam' },
  { code: '+967',  flag: '🇾🇪', label: 'Yémen' },
  { code: '+260',  flag: '🇿🇲', label: 'Zambie' },
  { code: '+263',  flag: '🇿🇼', label: 'Zimbabwe' },
]

// Sorted by code length descending for greedy prefix matching
const SORTED_PREFIXES = [...PHONE_PREFIXES].sort((a, b) => b.code.length - a.code.length)

// Parse a full phone number into prefix + local number
export function splitPhonePrefix(full: string | null, fallback = '+212'): { prefix: string; number: string } {
  if (!full) return { prefix: fallback, number: '' }
  for (const p of SORTED_PREFIXES) {
    if (full.startsWith(p.code)) return { prefix: p.code, number: full.slice(p.code.length) }
  }
  return { prefix: fallback, number: full }
}
