export interface Currency {
  code: string
  flag: string
  name: string
}

// Toutes les devises du monde, ordre alphabétique par code ISO 4217
export const WORLD_CURRENCIES: Currency[] = [
  { code: 'AED', flag: '🇦🇪', name: 'Dirham des Émirats arabes unis' },
  { code: 'AFN', flag: '🇦🇫', name: 'Afghani'                        },
  { code: 'ALL', flag: '🇦🇱', name: 'Lek albanais'                   },
  { code: 'AMD', flag: '🇦🇲', name: 'Dram arménien'                  },
  { code: 'ANG', flag: '🇸🇽', name: 'Florin antillais néerlandais'   },
  { code: 'AOA', flag: '🇦🇴', name: 'Kwanza angolais'                },
  { code: 'ARS', flag: '🇦🇷', name: 'Peso argentin'                  },
  { code: 'AUD', flag: '🇦🇺', name: 'Dollar australien'              },
  { code: 'AWG', flag: '🇦🇼', name: 'Florin d\'Aruba'                },
  { code: 'AZN', flag: '🇦🇿', name: 'Manat azerbaïdjanais'           },
  { code: 'BAM', flag: '🇧🇦', name: 'Mark convertible bosnien'       },
  { code: 'BBD', flag: '🇧🇧', name: 'Dollar barbadien'               },
  { code: 'BDT', flag: '🇧🇩', name: 'Taka bangladais'                },
  { code: 'BGN', flag: '🇧🇬', name: 'Lev bulgare'                    },
  { code: 'BHD', flag: '🇧🇭', name: 'Dinar de Bahreïn'               },
  { code: 'BIF', flag: '🇧🇮', name: 'Franc burundais'                },
  { code: 'BND', flag: '🇧🇳', name: 'Dollar de Brunéi'               },
  { code: 'BOB', flag: '🇧🇴', name: 'Boliviano'                      },
  { code: 'BRL', flag: '🇧🇷', name: 'Real brésilien'                 },
  { code: 'BSD', flag: '🇧🇸', name: 'Dollar des Bahamas'             },
  { code: 'BTN', flag: '🇧🇹', name: 'Ngultrum bhoutanais'            },
  { code: 'BWP', flag: '🇧🇼', name: 'Pula botswanais'                },
  { code: 'BZD', flag: '🇧🇿', name: 'Dollar bélizéen'                },
  { code: 'CAD', flag: '🇨🇦', name: 'Dollar canadien'                },
  { code: 'CDF', flag: '🇨🇩', name: 'Franc congolais'                },
  { code: 'CHF', flag: '🇨🇭', name: 'Franc suisse'                   },
  { code: 'CLP', flag: '🇨🇱', name: 'Peso chilien'                   },
  { code: 'CNY', flag: '🇨🇳', name: 'Yuan chinois'                   },
  { code: 'COP', flag: '🇨🇴', name: 'Peso colombien'                 },
  { code: 'CRC', flag: '🇨🇷', name: 'Colón costaricain'              },
  { code: 'CUP', flag: '🇨🇺', name: 'Peso cubain'                    },
  { code: 'CVE', flag: '🇨🇻', name: 'Escudo cap-verdien'             },
  { code: 'CZK', flag: '🇨🇿', name: 'Couronne tchèque'               },
  { code: 'DJF', flag: '🇩🇯', name: 'Franc djiboutien'               },
  { code: 'DKK', flag: '🇩🇰', name: 'Couronne danoise'               },
  { code: 'DOP', flag: '🇩🇴', name: 'Peso dominicain'                },
  { code: 'DZD', flag: '🇩🇿', name: 'Dinar algérien'                 },
  { code: 'EGP', flag: '🇪🇬', name: 'Livre égyptienne'               },
  { code: 'ERN', flag: '🇪🇷', name: 'Nakfa érythréen'                },
  { code: 'ETB', flag: '🇪🇹', name: 'Birr éthiopien'                 },
  { code: 'EUR', flag: '🇪🇺', name: 'Euro'                           },
  { code: 'FJD', flag: '🇫🇯', name: 'Dollar fidjien'                 },
  { code: 'GBP', flag: '🇬🇧', name: 'Livre sterling'                 },
  { code: 'GEL', flag: '🇬🇪', name: 'Lari géorgien'                  },
  { code: 'GHS', flag: '🇬🇭', name: 'Cedi ghanéen'                   },
  { code: 'GMD', flag: '🇬🇲', name: 'Dalasi gambien'                 },
  { code: 'GNF', flag: '🇬🇳', name: 'Franc guinéen'                  },
  { code: 'GTQ', flag: '🇬🇹', name: 'Quetzal guatémaltèque'          },
  { code: 'GYD', flag: '🇬🇾', name: 'Dollar guyanais'                },
  { code: 'HKD', flag: '🇭🇰', name: 'Dollar de Hong Kong'            },
  { code: 'HNL', flag: '🇭🇳', name: 'Lempira hondurien'              },
  { code: 'HRK', flag: '🇭🇷', name: 'Kuna croate'                    },
  { code: 'HTG', flag: '🇭🇹', name: 'Gourde haïtienne'               },
  { code: 'HUF', flag: '🇭🇺', name: 'Forint hongrois'                },
  { code: 'IDR', flag: '🇮🇩', name: 'Roupie indonésienne'            },
  { code: 'ILS', flag: '🇮🇱', name: 'Shekel israélien'               },
  { code: 'INR', flag: '🇮🇳', name: 'Roupie indienne'                },
  { code: 'IQD', flag: '🇮🇶', name: 'Dinar irakien'                  },
  { code: 'IRR', flag: '🇮🇷', name: 'Rial iranien'                   },
  { code: 'ISK', flag: '🇮🇸', name: 'Couronne islandaise'            },
  { code: 'JMD', flag: '🇯🇲', name: 'Dollar jamaïcain'               },
  { code: 'JOD', flag: '🇯🇴', name: 'Dinar jordanien'                },
  { code: 'JPY', flag: '🇯🇵', name: 'Yen japonais'                   },
  { code: 'KES', flag: '🇰🇪', name: 'Shilling kényan'                },
  { code: 'KGS', flag: '🇰🇬', name: 'Som kirghiz'                    },
  { code: 'KHR', flag: '🇰🇭', name: 'Riel cambodgien'                },
  { code: 'KMF', flag: '🇰🇲', name: 'Franc comorien'                 },
  { code: 'KPW', flag: '🇰🇵', name: 'Won nord-coréen'                },
  { code: 'KRW', flag: '🇰🇷', name: 'Won sud-coréen'                 },
  { code: 'KWD', flag: '🇰🇼', name: 'Dinar koweïtien'                },
  { code: 'KYD', flag: '🇰🇾', name: 'Dollar des Caïmans'             },
  { code: 'KZT', flag: '🇰🇿', name: 'Tenge kazakh'                   },
  { code: 'LAK', flag: '🇱🇦', name: 'Kip laotien'                    },
  { code: 'LBP', flag: '🇱🇧', name: 'Livre libanaise'                },
  { code: 'LKR', flag: '🇱🇰', name: 'Roupie sri-lankaise'            },
  { code: 'LRD', flag: '🇱🇷', name: 'Dollar libérien'                },
  { code: 'LSL', flag: '🇱🇸', name: 'Loti lésothan'                  },
  { code: 'LYD', flag: '🇱🇾', name: 'Dinar libyen'                   },
  { code: 'MAD', flag: '🇲🇦', name: 'Dirham marocain'                },
  { code: 'MDL', flag: '🇲🇩', name: 'Leu moldave'                    },
  { code: 'MGA', flag: '🇲🇬', name: 'Ariary malgache'                },
  { code: 'MKD', flag: '🇲🇰', name: 'Denar macédonien'               },
  { code: 'MMK', flag: '🇲🇲', name: 'Kyat birman'                    },
  { code: 'MNT', flag: '🇲🇳', name: 'Tögrög mongol'                  },
  { code: 'MOP', flag: '🇲🇴', name: 'Pataca de Macao'                },
  { code: 'MRU', flag: '🇲🇷', name: 'Ouguiya mauritanien'            },
  { code: 'MUR', flag: '🇲🇺', name: 'Roupie mauricienne'             },
  { code: 'MVR', flag: '🇲🇻', name: 'Rufiyaa maldivien'              },
  { code: 'MWK', flag: '🇲🇼', name: 'Kwacha malawien'                },
  { code: 'MXN', flag: '🇲🇽', name: 'Peso mexicain'                  },
  { code: 'MYR', flag: '🇲🇾', name: 'Ringgit malaisien'              },
  { code: 'MZN', flag: '🇲🇿', name: 'Metical mozambicain'            },
  { code: 'NAD', flag: '🇳🇦', name: 'Dollar namibien'                },
  { code: 'NGN', flag: '🇳🇬', name: 'Naira nigérian'                 },
  { code: 'NIO', flag: '🇳🇮', name: 'Córdoba nicaraguayen'           },
  { code: 'NOK', flag: '🇳🇴', name: 'Couronne norvégienne'           },
  { code: 'NPR', flag: '🇳🇵', name: 'Roupie népalaise'               },
  { code: 'NZD', flag: '🇳🇿', name: 'Dollar néo-zélandais'           },
  { code: 'OMR', flag: '🇴🇲', name: 'Rial omanais'                   },
  { code: 'PAB', flag: '🇵🇦', name: 'Balboa panaméen'                },
  { code: 'PEN', flag: '🇵🇪', name: 'Sol péruvien'                   },
  { code: 'PGK', flag: '🇵🇬', name: 'Kina papouasien'                },
  { code: 'PHP', flag: '🇵🇭', name: 'Peso philippin'                 },
  { code: 'PKR', flag: '🇵🇰', name: 'Roupie pakistanaise'            },
  { code: 'PLN', flag: '🇵🇱', name: 'Zloty polonais'                 },
  { code: 'PYG', flag: '🇵🇾', name: 'Guaraní paraguayen'             },
  { code: 'QAR', flag: '🇶🇦', name: 'Riyal du Qatar'                 },
  { code: 'RON', flag: '🇷🇴', name: 'Leu roumain'                    },
  { code: 'RSD', flag: '🇷🇸', name: 'Dinar serbe'                    },
  { code: 'RUB', flag: '🇷🇺', name: 'Rouble russe'                   },
  { code: 'RWF', flag: '🇷🇼', name: 'Franc rwandais'                 },
  { code: 'SAR', flag: '🇸🇦', name: 'Riyal saoudien'                 },
  { code: 'SBD', flag: '🇸🇧', name: 'Dollar salomonais'              },
  { code: 'SCR', flag: '🇸🇨', name: 'Roupie seychelloise'            },
  { code: 'SDG', flag: '🇸🇩', name: 'Livre soudanaise'               },
  { code: 'SEK', flag: '🇸🇪', name: 'Couronne suédoise'              },
  { code: 'SGD', flag: '🇸🇬', name: 'Dollar de Singapour'            },
  { code: 'SLL', flag: '🇸🇱', name: 'Leone sierra-léonais'           },
  { code: 'SOS', flag: '🇸🇴', name: 'Shilling somalien'              },
  { code: 'SRD', flag: '🇸🇷', name: 'Dollar surinamien'              },
  { code: 'SSP', flag: '🇸🇸', name: 'Livre sud-soudanaise'           },
  { code: 'STN', flag: '🇸🇹', name: 'Dobra sao-toméen'               },
  { code: 'SYP', flag: '🇸🇾', name: 'Livre syrienne'                 },
  { code: 'SZL', flag: '🇸🇿', name: 'Lilangeni swazilandais'         },
  { code: 'THB', flag: '🇹🇭', name: 'Baht thaïlandais'               },
  { code: 'TJS', flag: '🇹🇯', name: 'Somoni tadjik'                  },
  { code: 'TMT', flag: '🇹🇲', name: 'Manat turkmène'                 },
  { code: 'TND', flag: '🇹🇳', name: 'Dinar tunisien'                 },
  { code: 'TOP', flag: '🇹🇴', name: 'Pa\'anga tongan'                 },
  { code: 'TRY', flag: '🇹🇷', name: 'Livre turque'                   },
  { code: 'TTD', flag: '🇹🇹', name: 'Dollar trinidadien'             },
  { code: 'TWD', flag: '🇹🇼', name: 'Dollar taïwanais'               },
  { code: 'TZS', flag: '🇹🇿', name: 'Shilling tanzanien'             },
  { code: 'UAH', flag: '🇺🇦', name: 'Hryvnia ukrainienne'            },
  { code: 'UGX', flag: '🇺🇬', name: 'Shilling ougandais'             },
  { code: 'USD', flag: '🇺🇸', name: 'Dollar américain'               },
  { code: 'UYU', flag: '🇺🇾', name: 'Peso uruguayen'                 },
  { code: 'UZS', flag: '🇺🇿', name: 'Sum ouzbek'                     },
  { code: 'VES', flag: '🇻🇪', name: 'Bolívar vénézuélien'            },
  { code: 'VND', flag: '🇻🇳', name: 'Dong vietnamien'                },
  { code: 'VUV', flag: '🇻🇺', name: 'Vatu vanuatais'                 },
  { code: 'WST', flag: '🇼🇸', name: 'Tālā samoan'                    },
  { code: 'XAF', flag: '🇨🇲', name: 'Franc CFA CEMAC'                },
  { code: 'XCD', flag: '🇦🇬', name: 'Dollar des Caraïbes orientales' },
  { code: 'XOF', flag: '🇸🇳', name: 'Franc CFA UEMOA'                },
  { code: 'XPF', flag: '🇵🇫', name: 'Franc CFP'                      },
  { code: 'YER', flag: '🇾🇪', name: 'Rial yéménite'                  },
  { code: 'ZAR', flag: '🇿🇦', name: 'Rand sud-africain'              },
  { code: 'ZMW', flag: '🇿🇲', name: 'Kwacha zambien'                 },
  { code: 'ZWL', flag: '🇿🇼', name: 'Dollar zimbabwéen'              },
]

export const WORLD_CURRENCY_CODES = new Set(WORLD_CURRENCIES.map((c) => c.code))
